version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: database
    environment: 
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_USER: Clarusway_1 
      MYSQL_PASSWORD: bookstore_db
    networks:
      - clarusnet

  myapp:
    image: yasint23/bookstore-api:latest
    container_name: myapp
    restart: always
    depends_on: 
      - database
    ports:
      -"80:80"
    networks:
      - clarusnet
  
networks:
  clarusnet: 
