apiVersion: v1
kind: Secret
metadata: 
    name: mysql-secret
type: Opaque
data: 
    mysql-admin-password: Q2xhcnVzd2F5XzE=
    mysql-root-password: UjEyMzRy



# Sifrelerimiz Clarusway_1 ve R1234r ancak buraya encode ederek koyacagiz. Bunun icin terminalden asagidaki islemleri yapilip encode hali yazdik

#echo -n 'R1234r' | base64       ---->  mysql-root-password olarak mysql-secret.yaml dosyasında adreslenir
#echo -n 'Clarusway_1' | base64  ----> mysql-admin-password olarak mysql-secret.yaml dostasında adreslenir

# Clarusway_1 ve R1234r şifreleri decode etmek için
# echo -n 'UjEyMzRy' | base64 --decode     ---> It gives root us poassword
# echo -n 'Q2xhcnVzd2F5XzE=' | base64 --decode   ---> It gives us admin password