# As you see that playbook is become more simple with roles and this doc reusable, we can update postgre,nodejs etc. with new one.
# if the role folder is ready we can work only with this document.
- name: Docker install and configuration 
  hosts: _development
  become: true
  roles: 
    - docker
- name: Postgre Database configuration
  hosts: _ansible_postgresql
  become: true
  roles:
    - postgre
- name: Nodejs server configuration
  hosts: _ansible_nodejs
  become: true
  roles:
    - nodejs
- name: React UI Server configuration
  hosts: _ansible_react
  become: true
  roles:
    - react