apiVersion: v1
kind: ConfigMap
metadata: 
    name: servers_configmap
data: 
    MYSQL_DATABASE_HOST: mysql-service            # or 'mysql-service.default.svc.cluster.local' We don't use namespace /
    MYSQL_USER: clarus                            # / our name space default otherwise we need to write name space instead of 'default'
    MYSQL_DATABASE: phonebook


