apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
  template:
    metadata:
      name: mysql-pod 
      labels:
        name: mysql-pod                # This will be same in 'mysql_service.yaml' when we create.
    spec:
      containers:
      - image: mysql:5.7                 #From readme file
        name: mysql                      # We need to define env-var because in app.py file developer refer to write username, password with env var.
        imagePullPolicy: Always
        env:                             #Environment variables from docker hub given what is mandatory for mysql/ 
        - name: MYSQL_PASSWORD           #create secrets_configMap files then write env section
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-admin-password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        envFrom:                             # Take the database information from 'servers_configmap'
          - configMapRef:
              name: servers_configmap       
        ports:
        - containerPort: 3306                #From readme file
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim