apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi             # Skeleton of projects given
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"         # Skeleton of projects given